[package]
name = "dayz-tool-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.20", features = ["derive"] }
regex = "1.11.1"
sha2 = "0.10.8"
thiserror = "1.0.65"
