use base64::{engine::general_purpose, Engine as _};
use log::error;
use regex::Regex;
use sha2::{Digest, Sha256};

use crate::{GuidError, Result};

/// Generates a GUID from a given Steam64 ID.
///
/// The GUID is generated by hashing the Steam64 ID using SHA-256 and then
/// encoding the hash result in Base64.  The resulting Base64 string is then
/// modified by replacing all occurrences of "/" with "_" to create a valid GUID.
///
/// # Arguments
///
/// * `id` - The Steam64 ID to generate the GUID from.
///
/// # Returns
///
/// A String representing the generated GUID.
///
/// # Example
///
/// ```rust
/// use dayz_tool_cli::commands::generate_guid;
///
/// let steam64id = "76561198039479171";
/// let guid = generate_guid(steam64id);
///
/// assert_eq!(guid, "Bf_539q_w3ILhdEg8_kBACd4lKj-_ipXV8TiKEPj-og=");
/// ```
pub fn generate_guid(id: &str) -> String {
    let mut hasher = Sha256::new();

    match validate_id(id) {
        Ok(validated_id) => {
            hasher.update(validated_id);
            let hash_result = hasher.finalize();

            let hash_to_base64 = general_purpose::URL_SAFE.encode(hash_result);

            let base64_regex = Regex::new(r"/").unwrap();
            let guid = base64_regex.replace_all(&hash_to_base64, "_");

            guid.to_string()
        }
        Err(e) => {
            error!("{}", e);
            std::process::exit(1);
        }
    }
}

/// Validates a Steam64 ID.
///
/// # Arguments
///
/// * `id` - The Steam64 ID to validate.
///
/// # Returns
///
/// A Result containing the validated Steam64 ID as a String if successful, or an error if the Steam64 ID is invalid.
///
/// # Errors
///
/// Returns an error if the Steam64 ID is invalid. The following errors can occur:
///
/// * `InvalidLength`: The Steam64 ID is not 17 characters long.
/// * `InvalidPrefix`: The Steam64 ID does not start with "7656119".
/// * `InvalidCharacters`: The Steam64 ID contains invalid characters.
fn validate_id(id: &str) -> Result<String> {
    if id.len() != 17 {
        return Err(GuidError::InvalidLength);
    } else if !id.starts_with("7656119") {
        return Err(GuidError::InvalidPrefix);
    } else if !id.chars().all(|c| c.is_ascii_digit()) {
        return Err(GuidError::InvalidCharacters);
    }

    Ok(id.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_guid() {
        let steam64id: &str = "76561198039479171";
        let expected_guid = "Bf_539q_w3ILhdEg8_kBACd4lKj-_ipXV8TiKEPj-og=";
        let generated_guid = generate_guid(steam64id);
        assert_eq!(generated_guid, expected_guid);
    }

    #[test]
    fn test_validate_id_valid() {
        let valid_id = "76561198000000000";
        assert_eq!(validate_id(valid_id), Ok(valid_id.to_string()));
    }

    #[test]
    fn test_validate_id_invalid_length() {
        let invalid_id = "7656119800000000";
        assert_eq!(validate_id(invalid_id), Err(GuidError::InvalidLength));
    }

    #[test]
    fn test_validate_id_invalid_prefix() {
        let invalid_id = "86561198000000000";
        assert_eq!(validate_id(invalid_id), Err(GuidError::InvalidPrefix));
    }

    #[test]
    fn test_validate_id_invalid_characters() {
        let invalid_id = "76561198000000abc";
        assert_eq!(validate_id(invalid_id), Err(GuidError::InvalidCharacters));
    }
}
